---
resources:
- name: resource-web-app
  type: git
  source:
    uri: https://github.com/bookun/concourse-cf-sample.git

- name: resource-deploy-web-app
  type: cf
  source:
    api: ((api))
    username: ((username))
    password: ((password))
    organization: ((organization))
    space: ((space))
    skip_cert_check: false

jobs:
- name: job-deploy-app
  public: true
  plan:
  - get: resource-web-app
    trigger: true
  - task: build
    file: resource-web-app/tasks/build.yml
  - put: resource-deploy-web-app
    params:
      manifest: built/manifest.yml
      current_app_name: cf-sample
