---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
  - name: resource-web-app

caches:
  - path: resource-web-app/vendor

outputs:
  - name: built

run:
  path: ci/tasks/build.sh
  dir: resource-web-app
